# Generated by Django 4.2.7 on 2026-03-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
